README improvements
Rubberduckycooly/RSDKv5-Decompilation pull request #115
Opened 2022-10-09 03:31 UTC by santiagocezar

yeah this is not done yet, but as the title says, it adds a bit of more info to the READMEs

2022-10-10 00:22 UTC, santiagocezar commented
ok yeah it's pretty much done.

2022-11-15 03:40 UTC, MGRich requested changes

2022-11-15 03:40 UTC, MGRich commented on dependencies/android/README.md
> +The working directory will be at `[sdcard root]/RSDK/v5`. **Please note that GL shaders are required, or you will get a black screen.** Read the Shaders section in [the GL3 README](../../RSDKv5/Shade
States to see the shaders section in the GL3 readme, but still points to the shaders readme.

2022-11-15 04:16 UTC, MGRich commented on dependencies/android/README.md
> +The working directory will be at `[sdcard root]/RSDK/v5`. **Please note that GL shaders are required, or you will get a black screen.** Read the Shaders section in [the GL3 README](../../RSDKv5/Shade
wait i can do this myself i think

2022-11-15 04:46 UTC, merged